/**
 * Demo club catalog — lets a prospect see the app in *their* branding without
 * touching the database.
 *
 * The production path is unchanged: `getClubConfig()` reads `club_config` from
 * Supabase and that is what a real, paying club gets. This module is a parallel
 * read-only path used only when a `?club=<slug>` parameter is present, sourced
 * from a static JSON file generated by golf-db-product's `export_demo_catalog`.
 *
 * Why not just seed the database for each demo: onboarding 132 clubs into
 * `club_config` to show one of them would pollute the pilot's data, require a
 * migration per prospect, and risk a live demo hitting a half-written row.
 * A static catalog is instant, reversible and cannot corrupt the pilot.
 */
import catalog from './demo-clubs.json'
import type { ClubConfig, NavLink } from './club-config'

export type DemoClub = {
  slug: string
  club_name: string
  club_name_long: string
  state: string
  city: string
  location: string
  club_type: string
  primary_color: string
  secondary_color: string | null
  logo_path: string
  /**
   * How to render the logo on the dark header.
   *  - 'bare'  : transparent background, light artwork — draw directly.
   *  - 'plate' : opaque or dark artwork — draw on a white plate.
   * Measured per asset by golf-db-product's export_demo_catalog.py.
   */
  logo_treatment: 'bare' | 'plate'
  phone: string | null
  website_url: string | null
  tee_sheet_url: string | null
  tee_sheet_vendor: string | null
  billing_url: string | null
  staff_info_url: string | null
  course_par: number | null
  course_yardage: string | null
  nav_links: NavLink[]
  /** Lower = closer to Mansfield, MA. null = outside the target radius. */
  radius_rank: number | null
}

export const DEMO_CLUBS = catalog as DemoClub[]

const BY_SLUG = new Map(DEMO_CLUBS.map((c) => [c.slug, c]))

export function getDemoClub(slug: string | null | undefined): DemoClub | null {
  if (!slug) return null
  return BY_SLUG.get(slug) ?? null
}

/** Clubs inside the Mansfield target radius, nearest first. */
export function nearbyDemoClubs(): DemoClub[] {
  return DEMO_CLUBS.filter((c) => c.radius_rank !== null)
}

/**
 * Project a catalog entry onto the same shape the app already consumes, so
 * every page renders a demo club through the identical code path as the pilot.
 *
 * `course_id` is deliberately kept as the pilot's, because the demo reuses the
 * pilot's seeded rounds/events/feed content — the branding changes, the sample
 * data does not. That is the honest thing to show: a prospect is looking at
 * the product, not at their own member data, and we never imply otherwise.
 */
export function demoClubToConfig(demo: DemoClub, pilotCourseId: string): ClubConfig {
  return {
    course_id: pilotCourseId,
    club_name: demo.club_name,
    club_name_long: demo.club_name_long,
    primary_color: demo.primary_color,
    // null is fine — lib/theme.ts derives a contrast-safe accent from primary.
    secondary_color: demo.secondary_color ?? '',
    logo_path: demo.logo_path,
    location: demo.location,
    phone: demo.phone,
    website_url: demo.website_url,
    tee_sheet_url: demo.tee_sheet_url,
    billing_url: demo.billing_url,
    staff_info_url: demo.staff_info_url,
    menu_pdf_path: null,
    course_par: demo.course_par,
    course_yardage: demo.course_yardage,
    nav_links: demo.nav_links,
  }
}
